name: deploy by env
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 # CDK
        with:
          node-version: 18

  deploy_dev:
    name: Deploy to Dev
    needs: build
    if: github.ref_name != 'main'
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [[ $AWS_ACCESS_KEY_ID == dev* ]]; then
            echo "Correct AWS_ACCESS_KEY_ID"
          else
            echo "Incorrect AWS_ACCESS_KEY_ID"
          fi
          if [[ $AWS_SECRET_ACCESS_KEY == dev* ]]; then
            echo "Correct AWS_SECRET_ACCESS_KEY"
          else
            echo "Incorrect AWS_SECRET_ACCESS_KEY"
          fi
  deploy_prd:
    name: Deploy to Prd
    needs: build
    if: github.ref_name == 'main'
    environment: prd
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [[ $AWS_ACCESS_KEY_ID == prd* ]]; then
            echo "Correct AWS_ACCESS_KEY_ID"
          else
            echo "Incorrect AWS_ACCESS_KEY_ID"
          fi
          if [[ $AWS_SECRET_ACCESS_KEY == prd* ]]; then
            echo "Correct AWS_SECRET_ACCESS_KEY"
          else
            echo "Incorrect AWS_SECRET_ACCESS_KEY"
          fi
